# Generated by Django 4.1.4 on 2022-12-27 02:43

import django.core.validators
from django.db import migrations, models
import smart_media.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="", max_length=50, verbose_name="Title"),
                ),
                (
                    "media",
                    models.FileField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        upload_to="sample/media/%y/%m",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "svg", "gif", "png"]
                            )
                        ],
                        verbose_name="media",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        upload_to="sample/image/%y/%m",
                        verbose_name="Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image item",
                "verbose_name_plural": "Image items",
            },
            bases=(smart_media.mixins.SmartFormatMixin, models.Model),
        ),
    ]
