# Generated by Django 5.1.1 on 2024-09-28 15:19

import sandbox.sample.models
import smart_media.modelfields
import smart_media.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageitem",
            name="cover",
            field=smart_media.modelfields.SmartMediaField(
                blank=True,
                default=None,
                help_text="Implemented with SmartMediaField",
                max_length=255,
                null=True,
                upload_to="sample/cover/%y/%m",
                verbose_name="cover",
            ),
        ),
        migrations.AlterField(
            model_name="imageitem",
            name="image",
            field=models.ImageField(
                blank=True,
                default=None,
                help_text="Implemented with ImageField (SVG is not allowed)",
                max_length=255,
                null=True,
                upload_to=sandbox.sample.models.image_uploadto,
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="imageitem",
            name="mediafile",
            field=models.FileField(
                blank=True,
                default=None,
                help_text="Implemented with models.FileField and SmartMediaFileExtensionValidator",
                max_length=255,
                null=True,
                upload_to=sandbox.sample.models.media_uploadto,
                validators=[smart_media.validators.SmartMediaFileExtensionValidator()],
                verbose_name="media",
            ),
        ),
    ]
